name: 2.1 First Workflow #if not mentioned it will guve the relative path of the file
on: push

jobs:

    #name
    job_1:

        #where it runs
        runs-on: ubuntu-latest

        #steps
        steps:
            #runs in series
            - name: Welcome Message
              run: echo "1st flow"

            - name: List files
              run: echo ls

            - name: Read file
              run: cat README.md

