name: Variables and Secrets
on:
  workflow_dispatch: 
  # schedule:
  #   - cron: "*/1 * * * *"

env:
    DOCKER_USN: 11aashwin
    CONTAINER_REG: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:

    Docker:
        runs-on: ubuntu-latest


        steps:
            - name: Build
              run: echo docker build -t ${{env.CONTAINER_REG}}/$DOCKER_USN/$IMAGE_NAME:latest

            - name: Login
              run: echo docker login --username=$DOCKER_USN --password=${{secrets.DOCKER_PASS}}

            - name: Publish
              run: echo docker push $CONTAINER_REG/$DOCKER_USN/$IMAGE_NAME:latest

    Deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        concurrency: 
          group: production-deployment
          cancel-in-progress: true  #cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.
          
        timeout-minutes: 2
        needs: Docker
        steps:
            - name: Docker Run
              timeout-minutes: 1
              run: |
               sleep 600
               echo docker run -d -p 8000:8000 $CONTAINER_REG/$DOCKER_USN/$IMAGE_NAME:latest
              



