name: Debug demo

on:
  workflow_dispatch:
    inputs:
      run-test:
        descirption: "Run test"
        type: choice
        required: true
        options:
          - true
          - false
      test-type:
        descirption: "Write something"
        type: string
        required: true
      environment:
        descirption: "Choose the env"
        required: true
        type: environment

  # push:

env:
    USER_1: "hoo"
    USER_2: "joo"


jobs:

    hello:
        runs-on: ubuntu-latest
      
        steps:
          - name: Checkout
            uses: actions/checkout@v6
            
          - name: inputs values
            run: |
             echo "input 1: ${{ inputs.run-test }}"
             echo "input 2: ${{ inputs.test-type }}"
             echo "input 3: ${{ inputs.environment }}"

          - name: Event type
            if: ${{ inputs.run-test }}
            run: echo "${{ github.event_name }}"

          - name: Set user1 to github env
            run: echo " USERNAME= $USER_1" >> $GITHUB_ENV

          - name: Print USERNAME
            run: |
             echo "USERNAME .... $USERNAME"
          


          - name: PRINTING USER 2
            run: echo $USER_2