name: 2.7 Multiple Jobs, Needs,  #if not mentioned it will guve the relative path of the file
on: push

jobs:

    #name
    build_job_1: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v6


            #runs in series
            - name: Welcome Message | List and Read files
              run: |
                echo "1st flow"
                ls -ltra
                cat README.md
            
            - name: Install cowsay
              run: sudo apt-get install cowsay -y

            - name: Generate ASCII Content
              run: cowsay -f dragon "Run for cover, Im a dragon" >>dragon.txts

    test_job_2:
        runs-on: ubuntu-latest
        needs:  build_job_1

        steps:

            - name: Sleep
              run: sleep 10

            - name: Find dragon file
              run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [build_job_1,test_job_2]
        runs-on: ubuntu-latest

        steps:
            - name: Deploy
              run: echo "Deployed:

